output:
  path: "" # Substitute ""
  save_iter: 0
  best_model:
    do_get_best_model: True
    dataset: ""                     
    metric: "mAP@0.50"
    mode: "max"
is_cuda: True
random_seed: 0
init:
  model: ""                         
model:
  backbone_arch: ""                 
  use_inverse_geom_model: False     
  use_simplified_affine_model: True 
train:
  dataset_name: "tkh-train"          
  dataset_scale: 5500               
  objective:
    class_objective: "Torus"          
    loc_weight: 0.2                 
    positive_iou_threshold: 0.5     
    negative_iou_threshold: 0.1
    remap_classification_targets: True
    remap_classification_targets_iou_pos: 0.8
    remap_classification_targets_iou_neg: 0.4
  optim:
    anneal_lr:
      type: "MultiStepLR"
      milestones: [100000, 150000]
      gamma: 0.1

  model:
    freeze_bn: True
    freeze_bn_transform: True        
    train_transform_on_negs: False  
eval:
  iter: 2500
  dataset_names: ("tkh-val-new-cl",)  
  dataset_scales: (5500.0,)         
  mAP_iou_thresholds: (0.5,)
  